version: '3.7'

services:
  bot:
    build: .
    command: python run_bot.py
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_nt
    volumes:
      - .:/src
    environment:
      - TZ=Europe/Istanbul

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Istanbul
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    networks:
      - app_nt

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - TZ=Europe/Istanbul
    depends_on:
      - db
    networks:
      - app_nt


networks:
  app_nt:
    driver: bridge
volumes:
  postgres_data:
